---
title: "Homework 2"
author: "Ying Jin"
date: "2020/9/24"
output: github_document
---

This is the solution to homework 2!

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

Read and clean the Mr. Trash Wheel data:

```{r}
mr_trash_wheel_data <- read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "Mr. Trash Wheel",skip = 1,range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Read precipitation data:

```{r}
precip_2018 <- read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2018 Precipitation",skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 <- read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",sheet = "2017 Precipitation",skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Combine annual precipitation:

```{r}
month_df <- tibble(
  month = 1:12,
  month_name = month.name
)
precip_df <- bind_rows(precip_2017,precip_2018) %>% 
left_join( month_df, by = "month") %>% 
  select(-month) %>% 
  rename("month" ="month_name")
```

